import './styles.css'
import Header from './header'
import { SessionProvider } from 'next-auth/react'
import { getServerSession, Session } from 'next-auth'
import { headers } from 'next/headers'
import Providers from '../components/providers'
import { authOptions } from '../pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: {
  children: React.ReactNode
  session: any
}) {
  const session = await getServerSession(authOptions)
  console.log('session', session)
  return (
    <html lang="en">
      <body>
        {/* @ts-expect-error Async Server Component */}
        <Header key={'header'} />
        <Providers session={session}>
          {props.children}
        </Providers>

      </body>
    </html>
  )
}
